### Cadastrar um gênero
POST https://localhost:5001/genero/cadastrar
Content-Type: application/json

{
    "GeneroLivro" : "Terror"
}

### Listar os funcionários
GET https://localhost:5001/genero/listar