### Cadastrar cliente
POST https://localhost:5001/api/clientes/cadastrar
Content-Type: application/json

{
    "Nome": "Lucas",
    "Cpf": "123.4567.235-10"
}

### Listar clientes
GET https://localhost:5001/api/clientes/listar

### Buscar cliente
GET https://localhost:5001/api/clientes/buscar/10

### Editar cliente
PATCH  https://localhost:5001/api/clientes/editar
Content-Type: application/json

{
    "id": 2,
    "Nome": "Marcelo",
    "Cpf": "526.267.274-00"
}


### Deletar cliente
DELETE  https://localhost:5001/api/clientes/deletar/9

