### Cadastrar funcionario
POST https://localhost:5001/api/funcionarios/cadastrar
Content-Type: application/json

{
    "Nome": "Inacio",
    "Cpf": "098.765.543-01"
}


### Listar funcionarios
GET https://localhost:5001/api/funcionarios/listar

### Buscar funcionario
GET https://localhost:5001/api/funcionarios/buscar/3

### Editar funcionario
PATCH  https://localhost:5001/api/funcionarios/editar
Content-Type: application/json

{
    "id": 3,
    "Nome": "Marina",
    "Cpf": "123.546.978-31"
}

### Deletar funcionario
DELETE  https://localhost:5001/api/funcionarios/deletar/7

