### Cadastrar genero
POST https://localhost:5001/api/generos/cadastrar
Content-Type: application/json

{ "generoLivro": "Cincias"}


### Listar generos
GET https://localhost:5001/api/generos

### Buscar genero
GET https://localhost:5001/api/generos/listar/byId?id=10

### Editar genero
PATCH  https://localhost:5001/api/generos/editar/16
Content-Type: application/json

{ "generoLivo": "Romance" }

### Deletar genero
DELETE  https://localhost:5001/api/generos/deletar/15

