### Cadastrar livro
POST https://localhost:5001/api/livros/cadastrar
Content-Type: application/json

[
{
        "id": 1,
        "titulo": "O Hobbit",
        "autor": "JRR Tolkien",
        "publicacao": "0001-01-01T00:00:00",
        "paginas": 566,
        "isbn": "9781416550761",
        "editora": "Editor",
        "disponivel": true,
        "generoId": 3,
        "generos": null
    }
    ,    {
        "id": 2,
        "titulo": "Turma da monica jovem",
        "autor": "Mauricio de Souza",
        "publicacao": "0001-01-01T00:00:00",
        "paginas": 566,
        "isbn": "9781416550761",
        "editora": "Editor",
        "disponivel": true,
        "generoId": 3,
        "generos": null
    }
    ,    {
        "id": 3,
        "titulo": "Harry Potter",
        "autor": "JRR Tolkien",
        "publicacao": "1988-09-26T00:00:00",
        "paginas": 566,
        "isbn": "9781416550761",
        "editora": "Editor",
        "disponivel": true,
        "generoId": 3,
        "generos": null
    }
    ]

### Listar livros
GET https://localhost:5001/api/livros

### Buscar livro
GET https://localhost:5001/api/livros/buscar/2

### Editar livro
PATCH  https://localhost:5001/api/livros/editar
Content-Type: application/json

{
        "id": 3,
        "titulo": "Senhor dos aneis",
        "autor": "JRR Tolkien",
        "publicacao": "1988-09-26T00:00:00",
        "paginas": 566,
        "isbn": "9781416550761",
        "editora": "Editor",
        "disponivel": true,
        "generoId": 3,
        "generos": null
    }

### Deletar livro
DELETE  https://localhost:5001/api/livros/deletar/2

